title: code ninja . blog
description: where I show and discuss things I'm working on...
url: http://codeninja.blog/
baseurl: //

author:
  name: Jeff Massung
  email: massung@gmail.com
  github_username:  massung
  twitter_username: codeninja_blog

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
        layout: "post"

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: [jekyll-paginate]
exclude: [README.md, Gemfile, Gemfile.lock]
